---
apiVersion: v1
kind: Pod
metadata:
  name: dynamodb-local
  labels:
    app: dynamodb-local
spec:
  containers:
  - image: amazon/dynamodb-local:latest
    name: dynamodb-local
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: dynamodb-local-default-deny
spec:
  podSelector:
    matchLabels:
      app: dynamodb-local
  policyTypes:
  - Egress
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  labels:
    run: dynamodb-local
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: dynamodb-local
  selector:
    app: dynamodb-local
