apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity-agent
  labels:
    app: teamcity-agent
spec:
  selector:
    matchLabels:
      app: teamcity-agent
  template:
    metadata:
      labels:
        app: teamcity-agent
    spec:
      volumes:
      - name: agent-data
        hostPath:
          path: /teamcity-agent-data
          type: Directory
      containers:
      - name: teamcity-agent-container
        image: docker.io/jetbrains/teamcity-agent:latest
        volumeMounts:
        - name: agent-data
          mountPath: /data/teamcity_agent
        command:
        - sh
        - "-c"
        - |
          ( echo '{ "insecure-registries":["myregistry.example.com:5000"] }' > /etc/docker/daemon.json ) && \
            apt-get update && \
            apt-get install -y unzip libsodium-dev chromium-browser zip gettext-base python3.7-venv jq && \
            curl -o /tmp/gradle.zip -L https://services.gradle.org/distributions/gradle-5.3-bin.zip && \
            cd /usr/share && \
            unzip /tmp/gradle.zip && \
            cd / && \
            curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
            ( curl -s "https://get.sdkman.io" | bash ) && \
            source /root/.sdkman/bin/sdkman-init.sh && \
            sdkman install kotlin && \
            sdkman install kscript && \
            mv kubectl /usr/bin && \
            chmod a+x /usr/bin/kubectl && \
            curl -s -L -o /usr/bin/jq "https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64" && \
            chmod a+x /usr/bin/jq && \
            /run-services.sh
        securityContext:
          privileged: true
        env:
        - name: AGENT_NAME
          value: kube
        - name: DOCKER_IN_DOCKER
          value: start
        - name: GRADLE_HOME
          value: /usr/share/gradle-5.3
        - name: SERVER_URL
          value: http://10.0.88.160:8111

