---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - image: 10.0.88.166:32000/mariadbfun
    name: mariadb
    env:
    #- name: MARIADB_ALLOW_EMPTY_PASSWORD
    #  value: "1"
    - name: MYSQL_ROOT_PASSWORD
      value: "X2pZdnj2FNqmTPq"
    - name: MYSQL_DATABASE
      value: "hello"

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mariadb-default-deny
spec:
  podSelector:
    matchLabels:
      app: mariadb
  policyTypes:
  - Egress
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    run: mariadb
spec:
  type: LoadBalancer
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mariadb
  selector:
    app: mariadb

